services:
  mongodb:
    image: mongo
    container_name: mongo-service
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb

volumes:
  data: